### ISSUE TITLE
Task - Generate simplified geometry on-the-fly for returned objets - study

### ISSUE THREAD

**Issue by nick-rv** [benoitdm-oslandia/pg_featureserv#143]
* a geometry simplification capability has to be planned for the returned objects in order to reduce response size
* are concerned the responses with one feature or several features:
  * GET on a feature : /collections/{id}/items/{fid}
  * GET on a collection : /collections/{id}/items
  * GET on a collection with filter(s) ? : /collections/{id}/items

* An URL parameter representing the simplification level (Level Of Detail) needs to be implemented :
  * -> name : `max-allowable-offset` according to https://github.com/opengeospatial/ogcapi-features/issues/654
  * -> The value is in the units of the response coordinate reference system. (degree for 4326 SRID or meter for 2154 for example)
  * target function at postGIS level: `geometry ST_Simplify(geometry geomA, float tolerance, boolean preserveCollapsed);`

* Are excluded from this functionality all POINT and MULTIPOINT features
* Are concerned all the LINE / MULTILINE and  POLYGON / MULTIPOLYGON features

OGC Feature discussions :
https://github.com/opengeospatial/ogcapi-features/projects/13?card_filter_query=label%3A%22part+n%3A+geometry+simplification%22
https://github.com/opengeospatial/ogcapi-features/issues/654

**Comment by benoitdm-oslandia** [comment]
Please check [Postgis doc](https://www.google.com/search?q=site:postgis.net+inurl:docs+Douglas-Pecker)

**Comment by nick-rv** [comment]
It seems interesting to mention that The orb package is currently used by pg_featureserv.
And it seems interesting to mention that this component provides a simplification function like postgis does : https://github.com/paulmach/orb/tree/master/simplify#dp
In the case we face performance issues or overload on the database, this could represent a solution.
