### ISSUE TITLE
Task - Generate simplified geometry on-the-fly for returned objets - impl

### ISSUE THREAD

**Issue by benoitdm-oslandia** [benoitdm-oslandia/pg_featureserv#155]
Implementation phase following #143

**Comment by nick-rv** [comment]
The orb package is currently used by pg_featureserv.
And it seems interesting to mention that this component provides a simplification function like postgis does : https://github.com/paulmach/orb/tree/master/simplify#dp
In the case we face performance issues or overload on the database, this could represent a solution.
