### ISSUE TITLE
Task - create a test to validate support for twisted table/schema names

### ISSUE THREAD

**Issue by benoitdm-oslandia** [benoitdm-oslandia/pg_featureserv#55]
Test, and establish in the documentation, the possibility of using all the characters supported by postgresql

https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by jmkerloch** [comment]
@benoitdm-oslandia  @jacobpascalcoblentz @pramsey Should we support schema and table name with spaces ?

**Comment by pramsey** [comment]
I don't feel like you have much choice: PgSQL allows schema/table/column names with spaces as long as they are quoted. Some data importers happily create such things automatically. They *will* show up in the database, so read access *has* to handle them. You could disallow creation of them, but then you'd still need to be able to handle modification of them, in the case of pre-existing data. I think it is required.

**Comment by jmkerloch** [comment]
@pramsey do you have an idea of how user will request such schema/table/column ?

for example how do we request a schema/table `"schema with space"."table with space"`

Should it be `/collections/schema%20with%20space.table%20with%20space/items` ?

**Comment by pramsey** [comment]
You forgot the ever-popular "table with ."

Yes, clearly all the spaces should be URL encoded (although I'm pretty sure a lot of clients will auto-encode them, and sometimes servers will respond to URLs with spaces in them). More difficult will be handling periods that fall within table names.

```"myschema is great"."my table. she is better"```

We could try to define our way out of it, but I think the presence of the quotation marks disambiguates things sufficiently that it is possible to break out the components without any extra hints.

**Comment by benoitdm-oslandia** [comment]
In a previous project we rejected the use of "%", single quote or double quote in the schema and table names. For example we can have "@éôù 3AZ~ç§$µ" as a valid table name :fearful:... I have no seen any indication about utf-8 or utf-16 character restrictions in the postgresql documentation: this means we could have table name in Japanese Kanji !!!!

**Comment by pramsey** [comment]
![screenshot_1103](https://user-images.githubusercontent.com/113883/218522378-7995175e-885c-431a-bdc2-1cc3a0c66bd1.png)

**Comment by benoitdm-oslandia** [comment]
> ![screenshot_1103](https://user-images.githubusercontent.com/113883/218522378-7995175e-885c-431a-bdc2-1cc3a0c66bd1.png)

Your laptop is in fire!!!! Can you copy/paste the text version to see the exact name that have been used?

**Comment by pramsey** [comment]
Indeed! Actually I was pleased to see that not only are emoti-tables and columns allowed, but the automatically created dependent sequence also reflects the names.
