### ISSUE TITLE
Task - intégrer le couple schema + table pour les requêtes en base

### ISSUE THREAD

**Issue by benoitdm-oslandia** [benoitdm-oslandia/pg_featureserv#76]
In GitLab by @nrevelant on Oct 21, 2022, 11:13

**Comment by jmkerloch** [comment]
I think the support for schema.table is already implemented.

We are currently testing database with `complex.mock_multi` table.

@benoitdm-oslandia  I suggest we close this issue.

**Comment by benoitdm-oslandia** [comment]
Ok you're right!
