### ISSUE TITLE
Task - accept header superseds page suffix

### ISSUE THREAD

**Issue by benoitdm-oslandia** [benoitdm-oslandia/pg_featureserv#88]
even if an user choose to add a suffix (html/json) to a page name, if an accept header is defined then the suffix is ignored. The default behaviour for a web browser is to send an accept header misunderstood by the current code, so user will always retrieve json data when he asked for html ou other.

See also [#41](https://git.oslandia.net/Client-projects/geoplateforme-ign-pg-featureserv/-/merge_requests/41#note_285385)

**Comment by nick-rv** [comment]
- [x]  Manage default _Accept_ header value from common browsers
- [x] Accept header supersedes suffix if both are sent by client
- [x] json format remains the default
- [x] unsupported formats brings a NotAcceptable error when a GET request is sent on collection items(/collections/{collection}/items) or a specific item /collections/{collection}/items/{fid}
